name: trade101

description: The flutter project for selling books.




# Configuration for flutter_native_splash package
flutter_native_splash:
  # Background color for the splash screen
  color: "#F8B400"

  # Background color for the splash screen in dark mode
  color_dark: "#F8B400"

  # Image asset for the splash screen
  image: assets/logos/akili-logo.png

  # Image asset for the splash screen in dark mode
  image_dark: assets/logos/akili-logo.png

  # Configuration for Android 12 splash screen
  android_12:
    # Background color for the splash screen on Android 12
    color: "#F8B400"

    # Background color for the splash screen in dark mode on Android 12
    color_dark: "#F8B400"

    # Image asset for the splash screen on Android 12
    image: assets/logos/akili-logo.png

    # Image asset for the splash screen in dark mode on Android 12
    image_dark: assets/logos/akili-logo.png

  # Disable splash screen on the web platform~~~~~
  web: false


publish_to: 'Playstore'
version: 1.0.2

environment:
  sdk: '>=3.0.6 <4.0.0'


#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  dio: ^5.0.0 # For making HTTP requests
  path_provider: ^2.0.0 # For getting the storage directory
  permission_handler: ^10.0.0 # For handling permissions
  device_info_plus: ^9.0.2

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  firebase_core: ^2.27.0
  google_fonts: ^6.1.0
  blur: ^3.1.0
  lottie: ^3.1.0
  connectivity_plus: ^5.0.2
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.9
  cached_network_image: ^3.3.1
  wakelock_plus: ^1.1.4
  pdfx: ^2.6.0
  firebase_app_check: ^0.2.1+17
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.1
  shared_preferences: ^2.2.3
  upgrader: ^10.2.0
  syncfusion_flutter_charts: ^25.1.41+2
  #  awesome_notifications: ^0.8.2
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.1.1
  flutter_typeahead: ^5.2.0
  syncfusion_flutter_pdf: ^25.2.7
  file_picker: ^8.0.0+1
  path: ^1.8.3
  package_info_plus: ^4.2.0
  open_file: ^3.3.2


  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"












flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/books/
    - assets/images/onboarding/
    - assets/images/users/
    - assets/images/animations/


  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: SFPRODISPLAY
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 600
    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf
          weight: 400